### PR TITLE
[1.18] add support for NBT in icons

### PR DESCRIPTION
**Pull request by Minecraftschurli**
retargeted version of #11

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Hey @Minecraftschurli , I am currently in the process of relicensing Catalogue to a more suitable license. I would like your permission to relicense your contributions to Catalogue under MIT.

**Comment by MrCrayfish** [comment]
Unfortunately I have now removed your contributions and gone ahead with relicensing. Although I haven't received a reply back, I appreciate your support on this project. If you get around to reading this and accept the new license, I can reimplement your contributions.

**Comment by Minecraftschurli** [comment]
I thought I messaged you on discord saying it is ok

**Comment by MrCrayfish** [comment]
Where did you post this? I have DMs closed and search results on the server shows no messages from you regarding this issue.

**Pull request merged**
